import { ServiceCardType } from "./types";

export const serviceCards: ServiceCardType[] = [
  {
    id: "1",
    src: "/icons/cards/oven.svg",
    srcInverted: "/icons/cards/oven-inverted.svg",
    text: "oven",
    isMulti: false,
  },
  {
    id: "2",
    src: "/icons/cards/iron.svg",
    srcInverted: "/icons/cards/iron-inverted.svg",
    text: "iron",
    isMulti: true,
  },
  {
    id: "3",
    src: "/icons/cards/fridge.svg",
    srcInverted: "/icons/cards/fridge-inverted.svg",
    text: "fridge",
    isMulti: false,
  },
  {
    id: "4",
    src: "/icons/cards/balcony.svg",
    srcInverted: "/icons/cards/balcony-inverted.svg",
    text: "balcony",
    isMulti: false,
  },
  {
    id: "5",
    src: "/icons/cards/microwave.svg",
    srcInverted: "/icons/cards/microwave-inverted.svg",
    text: "microwave",
    isMulti: false,
  },
  // {
  //   id: "6",
  //   src: "/icons/cards/window.svg",
  //   srcInverted: "/icons/cards/window-inverted.svg",
  //   text: "window",
  //   isMulti: true,
  // },
  {
    id: "7",
    src: "/icons/cards/wardrobe.svg",
    srcInverted: "/icons/cards/wardrobe-inverted.svg",
    text: "wardrobe",
    isMulti: false,
  },
  {
    id: "8",
    src: "/icons/cards/pet.svg",
    srcInverted: "/icons/cards/pet-inverted.svg",
    text: "pet",
    isMulti: false,
  },
  {
    id: "9",
    src: "/icons/cards/plates.svg",
    srcInverted: "/icons/cards/plates-inverted.svg",
    text: "plates",
    isMulti: false,
  },
  {
    id: "10",
    src: "/icons/cards/blinds.svg",
    srcInverted: "/icons/cards/blinds-inverted.svg",
    text: "blinds",
    isMulti: true,
  },
  {
    id: "11",
    src: "/icons/cards/radiator.svg",
    srcInverted: "/icons/cards/radiator-inverted.svg",
    text: "radiator",
    isMulti: true,
  },
];

export const chemicalCleaningCards: ServiceCardType[] = [
  {
    id: "1",
    src: "/icons/cleaning-cards/sofa.svg",
    srcInverted: "/icons/cleaning-cards/sofa-inverted.svg",
    text: "sofa",
    isMulti: false,
  },
  {
    id: "2",
    src: "/icons/cleaning-cards/sofa-single.svg",
    srcInverted: "/icons/cleaning-cards/sofa-single-inverted.svg",
    text: "sofa-single",
    isMulti: false,
  },
  {
    id: "3",
    src: "/icons/cleaning-cards/armchair.svg",
    srcInverted: "/icons/cleaning-cards/armchair-inverted.svg",
    text: "armchair",
    isMulti: false,
  },
  {
    id: "4",
    src: "/icons/cleaning-cards/mattress.svg",
    srcInverted: "/icons/cleaning-cards/mattress-inverted.svg",
    text: "mattress",
    isMulti: false,
  },
  {
    id: "5",
    src: "/icons/cleaning-cards/sofa-corner.svg",
    srcInverted: "/icons/cleaning-cards/sofa-corner-inverted.svg",
    text: "sofa-corner",
    additionalQuestion: "sofa-corner-question",
    isMulti: true,
  },
  {
    id: "6",
    src: "/icons/cleaning-cards/carpet.svg",
    srcInverted: "/icons/cleaning-cards/carpet-inverted.svg",
    text: "carpet",
    isMulti: true,
  },
];
